# List of stages for jobs, and their order of execution
stages:
  - checkout
  - build
  - publish
  - stop_website
  - deploy
  - start_website

variables:
  BUILD_DIR: "C:\\Users\\Administrator\\Desktop\\Gitlab-CI\\src\\easycart\\src"
  PUBLISH_DIR : "C:\\Users\\Administrator\\Desktop\\Gitlab-CI\\artifacts"
  DEPLOY_DIR: "C:\\inetpub\\wwwroot\\publish"
  SITE_NAME: "Default Web Site"
  BRANCH: "main"

checkout:
  stage: checkout
  script:
    - cd $BUILD_DIR
    - git config --global safe.directory '*'
    - git checkout $BRANCH
    - git pull
  only:
    - main

build:
  stage: build
  script:
    - cd $BUILD_DIR
    - dotnet clean --configuration Release
    - dotnet restore
    - dotnet build --no-restore -c Release
  only:
    - main

publish:
  stage: publish
  environment: production
  script:
    - cd $BUILD_DIR
    - dotnet clean --configuration Release
    - dotnet restore
    - dotnet build --no-restore -c Release
    - cd Presentation/Nop.Web/
    - dotnet publish Nop.Web.csproj --no-build -c Release -o $PUBLISH_DIR /p:CopyRefAssembliesToPublishDirectory=true
  only:
    - main

stop-webiste:
  stage: stop_website
  script:
    - Stop-Website $SITE_NAME

deploy:
  stage: deploy
  script:
    - xcopy /y /s $PUBLISH_DIR $DEPLOY_DIR
  only:
    - main

start-website:
  stage: start_website
  script:
    - Start-Website $SITE_NAME
